name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Runs daily
  workflow_dispatch: # Manual trigger
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: activity, repositories
          repositories_affiliations: owner, collaborator, organization_member
          plugin_languages: yes
          plugin_followup: yes
          plugin_stargazers: yes
          plugin_traffic: yes
          output_action: commit
          committer_branch: main
