name: Metrics

on:
  schedule: [{ cron: "0 0 * * *" }]  # Runs daily
  workflow_dispatch:                # Allow manual trigger
  push: { branches: ["main"] }

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.33
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: activity, repositories
          repositories_affiliations: owner, collaborator, organization_member
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_categories: programming
          plugin_languages_ignored: html, css, shell
          plugin_languages_limit: 15
          plugin_languages_analysis_timeout: 60
          plugin_topics: yes
          plugin_isocalendar: yes
          plugin_notable: yes
          plugin_lines: yes
          config_output: metrics-main.svg
          output_action: commit
          committer_branch: main
